spring.application.name=PaymentServiceProvider
server.port=8081

#Database Conf
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/PSP
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.transaction=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.connection.isolation=2

#KEYSTORE CONFIG

server.ssl.key-store=classpath:psp-keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=psp
psp.password-secret=password


#PAYPAL config

paypal.client-id=AWki9cOJdLv6moxhc6ugm-28sUvCqAKobIf7dgeP2jGPT54HV_nig1-jwozeWNtYeWSVWR5M12pAdjm7
paypal.client-secret=EJj1lpSo8nyFsp7Cnrq-BlFdkm1rWY0_0I00APCLPqiSJZrTWBRN5ed_c67iAFw3ulniySU7TWinxTOh
paypal.mode=sandbox
paypal_api_url=https://api-m.sandbox.paypal.com


#BANK BASE URL

BANK_BASE_URL=https://localhost:8082/api/v1/bank

