spring.application.name=Bank
server.port=8082

#KEYSTORE CERTIFICATE CONFIG
server.ssl.enabled=true
server.ssl.key-store=classpath:bank-keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bank
psp.password-secret=password

#Database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Bank
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.transaction=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.connection.isolation=2


nbs_url=https://nbs.rs/QRcode/api/qr/v1/generate?lang=sr_RS_Latn
